controller.helix.cluster.name=pinot-local
controller.port=9000
controller.data.dir=/tmp/pinot/controller
controller.zk.str=lp-zk:2181
pinot.set.instance.id.to.hostname=true
pinot.controller.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
pinot.controller.storage.factory.s3.region=eu-west-1
pinot.controller.segment.fetcher.protocols=file,http,s3
